name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build and test (generates JaCoCo XML)
        run: mvn -B -e clean verify

      - name: SonarCloud Scan (debug)
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >-
            -X
            -Dsonar.organization=REPLACE_WITH_SONARCLOUD_ORG_KEY
            -Dsonar.projectKey=REPLACE_WITH_SONARCLOUD_PROJECT_KEY
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
