name: Build and Analyze

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17 with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build and test (generates JaCoCo XML)
        run: mvn --batch-mode clean verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud@v1
        with:
          args: >
            -Dsonar.projectKey=varunusstaffing043-sketch_Sai-
            -Dsonar.organization=varunusstaffing043-sketch
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
