name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build and test (generates JaCoCo XML)
        run: mvn -B -e clean verify

      # Creates the SonarCloud project if missing and outputs keys
      - name: Setup SonarCloud
        id: setupSonar
        uses: nelsoncanarinho/setup-sonar@v1.0.0
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Scan (debug)
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >-
            -X
            -Dsonar.organization=${{ steps.setupSonar.outputs.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ steps.setupSonar.outputs.SONAR_PROJECT_KEY }}
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
